alias ..='cd ..'
alias ....='cd ../..'
alias aa='sublime ~/.bash_aliases'
alias bb='google-chrome &'
alias bye='sudo shutdown -P now'
alias c='clear'
alias cma='chmod -R 777'
alias cmw='chmod -R a+w'
alias cmx='chmod -R +x'
alias cp='cp -prf'
alias d='meld'
alias e='echo'
alias ee='eclipse &'
alias ff='firefox &'
alias g='grep -i'
alias ga='git add'
alias gaa='git add .'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit -am'
alias gd='git diff'
alias gg='cd ~/Projects/github'
alias gh='git stash'
alias gi='less ~/.bash_aliases | grep -i git'
alias gl='git log --oneline'
alias gm='git commit --amend'
alias gn='git clone'
alias go='git checkout'
alias gp='git push'
alias gs='git show'
alias gt='git status -sb'
alias gu='git pull'
alias h='history'
alias j='jobs'
alias l='ls -Fghl'                       # normal
alias la='ls -AFghl'                     # all
alias ld='ls -AFghl | grep ^d'           # all dir
alias ldt='ls -AFghlt | grep ^d'         # all dir + time
alias lf='ls -AFghl | grep -v ^d'        # all file
alias lft='ls -AFghlt | grep -v ^d'      # all file + time
alias lh='ls -AdFghl .*'                 # hidden
alias lhd='ls -AdFghl .* | grep ^d'      # hidden dir
alias lhdt='ls -AdFghlt .* | grep ^d'    # hidden dir + time
alias lhf='ls -AdFghl .* | grep -v ^d'   # hidden file
alias lhft='ls -AdFghlt .* | grep -v ^d' # hidden file + time
alias lt='ls -Fghlt'                     # normal + time
alias lht='ls -AdFghlt .*'               # hidden + time
alias m='less -r'
alias mm='gnome-system-monitor &'
alias md='mkdir -p'
alias nap='sudo reboot'
alias ngit='rm -rf `find . -type d -name .git`'
alias ns='mv \!* `echo \!* | tr " " "_"`'
alias nsvn='rm -rf `find . -type d -name .svn`'
alias nt='rm -vf *~ .*~'
alias o='sublime'
alias oo='sublime &'
alias open='nautilus'
alias p='pwd'
alias r='rm -f'
alias rmd='rm -rf'
alias sc='source ~/.bash_aliases'
alias sq='sort | uniq'
alias st='svn status'
alias t='touch'
alias tt='tree'
alias u='unlink'
alias w='which'
