if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

PATH=/usr/local/sbin:/usr/local/bin:./node_modules/.bin:$PATH:$HOME/bin:$HOME/.node/bin
export PATH
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
