;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"

..=cd ..
....=cd .. && cd ..
adb="C:\Program Files (x86)\Android\android-sdk\platform-tools\adb" $*
c=clear
e=echo $*
ga=git add $*
gaa=git add .
gb=git branch $*
gba=git branch -a $*
gc=git commit $*
gca=git commit -a
gd=git diff $*
gh=git stash $*
gi=git init
gl=git log --oneline
gm=git merge $*
gn=git clone $*
go=git checkout $*
gp=git push $*
gs=git show $*
gt=git status -sb
gu=git pull -p
l=ls -alGh --show-control-chars -F --color $*
m=less $*
md=mkdir $*
ng=cd C:\Users\Tery Lim\source\repos
o=explorer $*
rmd=rm -rf $*
t=touch $*
v=vim $*
w=which $*
